name: build test

on:
  pull_request:
    branches: ["main"]

jobs: 
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: "npm"
      - name: "print version"
        run: npm --v      
      - name: "print node version"
        run: node -v
      - name: "Install packages"
        run: npm i      
      - name: "Install packages (again)"
        run: npm i
      - name: "Build packages"
        run: npm run build